align_depth: True
clip_distance: 3.0
color_width: 848
color_height: 480
color_fps: 60.0
depth_width: 848
depth_height: 480
depth_fps: 60.0
infra_width: 848
infra_height: 480
infra_fps: 60.0
enable_pointcloud: True
dense_pointcloud: True
enable_fisheye: False
enable_fisheye1: False
enable_fisheye2: False
enable_gyro: False
enable_accel: False
enable_pose: False
enable_sync: True
# device_type: 'd435'
initial_reset: True
rgb_camera:
    auto_exposure_priority: True
    backlight_compensation: True
    enable_auto_exposure: True
    enable_auto_white_balance: True
    frames_queue_size: 16
    power_line_frequency: 1
    saturation: 71
    sharpness: 74
stereo_module:
    emitter_always_on: False
    emitter_enabled: 2
    emitter_on_off: False
    enable_auto_exposure: True
    error_polling_enabled: True
    frames_queue_size: 16
    inter_cam_sync_mode: 0
    laser_power: 150.0
    visual_preset: 4  # 3=hi-acc; 4=hi-dens
pointcloud:
    frames_queue_size: 16
    filter_magnitude: 2
allow_no_texture_points: False
