_BASE_: "../COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml"
MODEL:
  BACKBONE: 
    FREEZE_AT: 3 #crow: freeze model at layer, default 2
  ANCHOR_GENERATOR:
#    SIZES: [[8], [32], [64], [128], [256]]  # One size for each in feature map #crow 7x7 is our minimal object - nut
    ASPECT_RATIOS: [[0.1, 0.25, 0.5, 1.0, 2.0, 4.0, 10.0]]  # aspect ratios (same for all in feature maps) #crow - we have long objects (screw,..)
    ANGLES: [[-90, -45, 0, 45, 90]]
  PROPOSAL_GENERATOR:
    MIN_SIZE: 7 #crow
  RPN:
    BBOX_REG_LOSS_TYPE: "giou"
    BBOX_REG_LOSS_WEIGHT: 2.0
    BOUNDARY_THRESH: 40000
    IOU_THRESHOLDS: [0.3, 0.8] #crow
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: "giou"
    BBOX_REG_LOSS_WEIGHT: 10.0
SOLVER:
  STEPS: (80000, 100000)
  MAX_ITER: 120000
  CHECKPOINT_PERIOD: 2000
  IMS_PER_BATCH: 10
  BASE_LR: 0.001 
  REFERENCE_WORLD_SIZE: 1 #propagetes to LR, BATCH with NUM_GPUS
INPUT:
  MIN_SIZE_TRAIN: (480,) #crow fixed sizes to cams' resolution 640x480
  MAX_SIZE_TRAIN: 480
  MIN_SIZE_TEST: 0 #crow disables resize in testing
  MASK_FORMAT: "polygon"  # alternative: "bitmask"
  CROP:
    SIZE: [0.8, 0.8]
TEST:
  EVAL_PERIOD: 0 #FIXME temporarily disabled, eval crashes on unknown class_id
  DETECTIONS_PER_IMAGE: 15
DATALOADER:
  NUM_WORKERS: 4 #crow: reduces mem footprint, but at cost of throughput
CUDNN_BENCHMARK: True
VIS_PERIOD: 10
