name: ros2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  #ROS2
  - python~=3.6.7 #python version must match internal python ver used in ROS, Eloquent has 3.6; also 3.6.0 is buggy.
  - conda-build
    #- conda-forge::wstool #for updating and installing .rosinstall dependencies
    #  - conda-forge::rosdep #tool for downloading ros dependencies
    #  - conda-forge::colcon-ros # ROS2 pkg build system 
  - pip
  # YOLACT
  - pytorch::pytorch>=1.0.1
  - pytorch::torchvision
  - cython
  - cudatoolkit
  - cudnn
  - pytorch::cuda100
  - matplotlib
  - git # to download COCO dataset
  - curl # to download COCO dataset
  - unzip # to download COCO dataset
  - conda-forge::bash # to download COCO dataset
  - pip:
    - opencv-contrib-python #we must use the contrib version for aruco etc
    - pillow <7.0 # bug PILLOW_VERSION in torchvision, must be < 7.0 until torchvision is upgraded
    - pycocotools
    - PyQt5 # needed on KDE/Qt envs for matplotlib
    - commentjson
    - pyrealsense2
    - filterpy
    - dill # YOLACT
    - catkin_pkg #for ROS
    - scipy #ROS calibrator
    - filterpy #ROS filter
    - transforms3d #ROS calibrator
    - open3d==0.10.0 #locator 
