## env for runnning all our ROS2 (ROS1) nodes. 
# You need to add the conda paths to python path before building, do so by: 
# export PYTHONPATH=/home/imitrob/anaconda3/envs/ros2/lib/python3.6/site-packages/:$PYTHONPATH
name: ros2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  #ROS2
  - python~=3.6.7 #python version must match internal python ver used in ROS, Eloquent has 3.6; also 3.6.0 is buggy.
  - conda-build
  - conda-forge::wstool #for updating and installing .rosinstall dependencies
  - conda-forge::rosdep #tool for downloading ros dependencies
  - conda-forge::colcon-ros # ROS2 pkg build system 
  - pip
  # YOLACT
  - pytorch::pytorch>=1.0.1
  - pytorch::torchvision
  - cython
  - cudatoolkit
  - cudnn
  - pytorch::cuda100
  - git # to download COCO dataset
  - curl # to download COCO dataset
  - unzip # to download COCO dataset
  - conda-forge::bash # to download COCO dataset
  - eigen #for realsense-ros repo
  - pip:
    - numpy
    - opencv-contrib-python #we must use the contrib version for aruco etc
    - pillow <7.0 # bug PILLOW_VERSION in torchvision, must be < 7.0 until torchvision is upgraded
    - pycocotools
    - PyQt5 # needed on KDE/Qt envs for matplotlib
    - commentjson
    - pyrealsense2
    - filterpy
    - dill # YOLACT
    - catkin_pkg #for ROS
    - scipy #ROS calibrator
    - filterpy #ROS filter
    - transforms3d #ROS calibrator
    - open3d==0.10.0 #locator 
    - empy # realsense_msgs fail with 'em', we need empy instead! 
    - matplotlib==2.1.1 #must match apt version installed by ROS2
